---
- hosts: toconfigure
  remote_user: rootless
  tasks:
    - name: Install rootless SSH key access
      authorized_key: >
        key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        user=rootless

    - name: Install root SSH key access
      authorized_key: >
        key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        user=root
      sudo: yes

    - name: Disable rootless password
      shell: passwd -d rootless
      sudo: yes

  