---
- hosts: nbica-servers
  remote_user: root
    
  roles: 
    - { role: aptproxy-server }
    - { role: proxydhcp-server }
    - { role: pxelinux-server }

  handlers:
    - include: roles/proxydhcp-server/handlers/handlers.yml